### ISSUE TITLE
encoder  dont sent  videos  anymore

### ISSUE THREAD

**Issue by mikweb2017** [YouPHPTube/YouPHPTube#2315]
i have all  uptodate
encoder  dont sent  videos  anymore
logs Encoder

03-Dec-2019 16:45:12 UTC] decideFormatOrder: {"videoURL":"https:\/\/www.youtube.com\/watch?v=Q6eTlmkCYwk","audioOnly":"false","spectrum":"false","webm":"false","inputHLS":"false","inputLow":"true","inputSD":"true","inputHD":"true","categories_id":"0"}
[03-Dec-2019 16:45:12 UTC] decideFormatOrder: MP4 All
[03-Dec-2019 16:45:12 UTC] Encoder::sendFile videos_id=0, format=mp4
[03-Dec-2019 16:45:12 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[03-Dec-2019 16:45:12 UTC] PHP Warning:  file_exists(): open_basedir restriction in effect. File(/usr/local/bin/youtube-dl) is not within the allowed path(s): (/var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/:/tmp/) in /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/objects/Encoder.php on line 1290
[03-Dec-2019 16:45:14 UTC] Encoder::sendFile sending file to https://you-tube.eu/youPHPTubeEncoder.json
[03-Dec-2019 16:45:14 UTC] Encoder::sendFile reading file from 
[03-Dec-2019 16:45:14 UTC] YouPHPTube-Streamer answer 
[03-Dec-2019 16:45:14 UTC] {"error":false,"format":"mp4","file":"","resolution":"","videoDownloadedLink":"https:\/\/www.youtube.com\/watch?v=Q6eTlmkCYwk","target":"https:\/\/you-tube.eu\/youPHPTubeEncoder.json","postFields":11,"response_raw":"","response":null}
[03-Dec-2019 16:45:14 UTC] Encoder::save id=() title=(More Office Pranks | Cartoon Box 157 | Hilarious Workplace Bullying Cartoon)[{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/view\/youtubeDl.json.php","line":76,"function":"save","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/view\/youtubeDl.json.php","line":116,"function":"addVideo","args":["https:\/\/www.youtube.com\/watch?v=Q6eTlmkCYwk","3"]}]
[03-Dec-2019 16:45:16 UTC] getReturn_vars {}
[03-Dec-2019 16:45:16 UTC] Encoder::save id=(11) title=(More Office Pranks | Cartoon Box 157 | Hilarious Workplace Bullying Cartoon)[{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/objects\/Encoder.php","line":532,"function":"save","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/view\/run.php","line":6,"function":"run","class":"Encoder","type":"::","args":[]}]
[03-Dec-2019 16:45:16 UTC] downloadFile: start queue_id = 11
[03-Dec-2019 16:45:16 UTC] downloadFile: url = https://www.youtube.com/watch?v=Q6eTlmkCYwk
[03-Dec-2019 16:45:16 UTC] getYoutubeDl: Getting from Youtube DL /usr/local/bin/youtube-dl  --no-check-certificate --force-ipv4 --no-check-certificate --no-playlist -k -o /tmp/youtubeDldfwCB3.mp4 -f 'mp4' "https://www.youtube.com/watch?v=Q6eTlmkCYwk"
[03-Dec-2019 16:45:19 UTC] getYoutubeDl: Copying [/tmp/youtubeDldfwCB3.mp4] to [/var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile.mp4] 
[03-Dec-2019 16:45:19 UTC] downloadFile:getYoutubeDl queue_id = 11
[03-Dec-2019 16:45:19 UTC] downloadFile: success
[03-Dec-2019 16:45:19 UTC] Encoder::save id=(11) title=(More Office Pranks | Cartoon Box 157 | Hilarious Workplace Bullying Cartoon)[{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/objects\/Encoder.php","line":276,"function":"save","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/objects\/Encoder.php","line":533,"function":"downloadFile","class":"Encoder","type":"::","args":["11"]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/view\/run.php","line":6,"function":"run","class":"Encoder","type":"::","args":[]}]
[03-Dec-2019 16:45:19 UTC] downloadFile: {"error":false,"filename":"11_tmpFile.mp4","pathFileName":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/videos\/11_tmpFile.mp4"}
[03-Dec-2019 16:45:19 UTC] Encoder::save id=(11) title=(More Office Pranks | Cartoon Box 157 | Hilarious Workplace Bullying Cartoon)[{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/objects\/Encoder.php","line":550,"function":"save","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/view\/run.php","line":6,"function":"run","class":"Encoder","type":"::","args":[]}]
[03-Dec-2019 16:45:19 UTC] PHP Notice:  Undefined property: stdClass::$videos_id in /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/objects/Encoder.php on line 552
[03-Dec-2019 16:45:19 UTC] sendImages: Sending image to []
[03-Dec-2019 16:45:19 UTC] Duration found: 0:01:41
[03-Dec-2019 16:45:19 UTC] sendImages: YouPHPTube-Encoder sending file to https://you-tube.eu/objects/youPHPTubeEncoderReceiveImage.json.php
[03-Dec-2019 16:45:19 UTC] sendImages: YouPHPTube-Encoder reading file from /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile.mp4
[03-Dec-2019 16:45:21 UTC] getThumbsFromLink: /usr/local/bin/youtube-dl  --no-check-certificate --no-playlist --force-ipv4 --write-thumbnail --skip-download  -o "/tmp/thumbsIpMbAh.jpg" "https://www.youtube.com/watch?v=Q6eTlmkCYwk"
[03-Dec-2019 16:45:21 UTC] getGifImage
[03-Dec-2019 16:45:21 UTC] getGif: Starts
[03-Dec-2019 16:45:22 UTC] getGif: takes 0.37996816635132 sec to complete
[03-Dec-2019 16:45:22 UTC] getWebpImage
[03-Dec-2019 16:45:22 UTC] getWebpImage: Starts
[03-Dec-2019 16:45:24 UTC] getWebpImage: takes 1.5379920005798 sec to complete
[03-Dec-2019 16:45:24 UTC] sendImages: curl_init
[03-Dec-2019 16:45:24 UTC] sendImages: curl_exec
[03-Dec-2019 16:45:24 UTC] sendImages: YouPHPTube-Streamer answer 
[03-Dec-2019 16:45:24 UTC] {"error":false,"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/videos\/11_tmpFile.mp4","target":"https:\/\/you-tube.eu\/objects\/youPHPTubeEncoderReceiveImage.json.php","postFields":7,"response_raw":"","response":null}
[03-Dec-2019 16:45:24 UTC] PHP Notice:  Trying to get property of non-object in /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/objects/Encoder.php on line 916
[03-Dec-2019 16:45:24 UTC] run:runMultiResolution
[03-Dec-2019 16:45:24 UTC] YouPHPTube-Encoder Start Encoder [ffmpeg -i /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile.mp4 -vf scale=-2:720 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -max_muxing_queue_size 1024 -y /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile_converted_HD.mp4] 
[03-Dec-2019 16:45:43 UTC] YouPHPTube-Encoder Start Encoder [ffmpeg -i /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile.mp4 -vf scale=-2:540 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -max_muxing_queue_size 1024 -y /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile_converted_SD.mp4] 
[03-Dec-2019 16:45:58 UTC] YouPHPTube-Encoder Start Encoder [ffmpeg -i /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile.mp4 -vf scale=-2:360 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -max_muxing_queue_size 1024 -y /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile_converted_Low.mp4] 
[03-Dec-2019 16:46:08 UTC] getReturn_vars {}
[03-Dec-2019 16:46:08 UTC] Encoder::save id=(11) title=(More Office Pranks | Cartoon Box 157 | Hilarious Workplace Bullying Cartoon)[{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/objects\/Encoder.php","line":688,"function":"save","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/objects\/Encoder.php","line":579,"function":"send","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/view\/run.php","line":6,"function":"run","class":"Encoder","type":"::","args":[]}]
[03-Dec-2019 16:46:08 UTC] Encoder::send() order_id=80
[03-Dec-2019 16:46:08 UTC] Encoder::send() multiResolutionOrder
[03-Dec-2019 16:46:08 UTC] Encoder::sendFile videos_id=0, format=mp4
[03-Dec-2019 16:46:08 UTC] Duration found: 0:01:41
[03-Dec-2019 16:46:10 UTC] Encoder::sendFile sending file to https://you-tube.eu/youPHPTubeEncoder.json
[03-Dec-2019 16:46:10 UTC] Encoder::sendFile reading file from /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile_converted_HD.mp4
[03-Dec-2019 16:46:11 UTC] YouPHPTube-Streamer answer 
[03-Dec-2019 16:46:11 UTC] {"error":false,"format":"mp4","file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/videos\/11_tmpFile_converted_HD.mp4","resolution":"HD","videoDownloadedLink":"https:\/\/www.youtube.com\/watch?v=Q6eTlmkCYwk","target":"https:\/\/you-tube.eu\/youPHPTubeEncoder.json","postFields":12,"videoFileSize":"21.23MB","response_raw":"","response":null}
[03-Dec-2019 16:46:11 UTC] PHP Notice:  Trying to get property of non-object in /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/objects/Encoder.php on line 840
[03-Dec-2019 16:46:11 UTC] Encoder::sendFile videos_id=0, format=mp4
[03-Dec-2019 16:46:11 UTC] Duration found: 0:01:41
[03-Dec-2019 16:46:13 UTC] Encoder::sendFile sending file to https://you-tube.eu/youPHPTubeEncoder.json
[03-Dec-2019 16:46:13 UTC] Encoder::sendFile reading file from /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile_converted_SD.mp4
[03-Dec-2019 16:46:14 UTC] YouPHPTube-Streamer answer 
[03-Dec-2019 16:46:14 UTC] {"error":false,"format":"mp4","file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/videos\/11_tmpFile_converted_SD.mp4","resolution":"SD","videoDownloadedLink":"https:\/\/www.youtube.com\/watch?v=Q6eTlmkCYwk","target":"https:\/\/you-tube.eu\/youPHPTubeEncoder.json","postFields":12,"videoFileSize":"15.46MB","response_raw":"","response":null}
[03-Dec-2019 16:46:14 UTC] PHP Notice:  Trying to get property of non-object in /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/objects/Encoder.php on line 840
[03-Dec-2019 16:46:14 UTC] Encoder::sendFile videos_id=0, format=mp4
[03-Dec-2019 16:46:14 UTC] Duration found: 0:01:41
[03-Dec-2019 16:46:16 UTC] Encoder::sendFile sending file to https://you-tube.eu/youPHPTubeEncoder.json
[03-Dec-2019 16:46:16 UTC] Encoder::sendFile reading file from /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile_converted_Low.mp4
[03-Dec-2019 16:46:16 UTC] YouPHPTube-Streamer answer 
[03-Dec-2019 16:46:16 UTC] {"error":false,"format":"mp4","file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/videos\/11_tmpFile_converted_Low.mp4","resolution":"Low","videoDownloadedLink":"https:\/\/www.youtube.com\/watch?v=Q6eTlmkCYwk","target":"https:\/\/you-tube.eu\/youPHPTubeEncoder.json","postFields":12,"videoFileSize":"9.18MB","response_raw":"","response":null}
[03-Dec-2019 16:46:16 UTC] PHP Notice:  Trying to get property of non-object in /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/objects/Encoder.php on line 840
[03-Dec-2019 16:46:16 UTC] Autodelete Not active
[03-Dec-2019 16:46:16 UTC] Encoder::save id=(11) title=(More Office Pranks | Cartoon Box 157 | Hilarious Workplace Bullying Cartoon)[{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/objects\/Encoder.php","line":744,"function":"save","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/objects\/Encoder.php","line":579,"function":"send","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/view\/run.php","line":6,"function":"run","class":"Encoder","type":"::","args":[]}]
[03-Dec-2019 16:46:17 UTC] Autodelete Not active
[03-Dec-2019 16:46:17 UTC] getReturn_vars {}
[03-Dec-2019 16:46:17 UTC] {}
[03-Dec-2019 16:46:17 UTC] Encoder::save id=(11) title=(More Office Pranks | Cartoon Box 157 | Hilarious Workplace Bullying Cartoon)[{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/objects\/Encoder.php","line":595,"function":"save","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/view\/run.php","line":6,"function":"run","class":"Encoder","type":"::","args":[]}]
[03-Dec-2019 16:49:37 UTC] getReturn_vars {}
[03-Dec-2019 16:49:37 UTC] Encoder::save id=(11) title=(More Office Pranks | Cartoon Box 157 | Hilarious Workplace Bullying Cartoon)[{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/objects\/Encoder.php","line":688,"function":"save","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/view\/send.json.php","line":20,"function":"send","class":"Encoder","object":{},"type":"->","args":[]}]
[03-Dec-2019 16:49:37 UTC] Encoder::send() order_id=80
[03-Dec-2019 16:49:37 UTC] Encoder::send() multiResolutionOrder
[03-Dec-2019 16:49:37 UTC] Encoder::sendFile videos_id=0, format=mp4
[03-Dec-2019 16:49:37 UTC] Duration found: 0:01:41
[03-Dec-2019 16:49:37 UTC] PHP Warning:  file_exists(): open_basedir restriction in effect. File(/usr/local/bin/youtube-dl) is not within the allowed path(s): (/var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/:/tmp/) in /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/objects/Encoder.php on line 1290
[03-Dec-2019 16:49:39 UTC] Encoder::sendFile sending file to https://you-tube.eu/youPHPTubeEncoder.json
[03-Dec-2019 16:49:39 UTC] Encoder::sendFile reading file from /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile_converted_HD.mp4
[03-Dec-2019 16:49:40 UTC] YouPHPTube-Streamer answer 
[03-Dec-2019 16:49:40 UTC] {"error":false,"format":"mp4","file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/videos\/11_tmpFile_converted_HD.mp4","resolution":"HD","videoDownloadedLink":"https:\/\/www.youtube.com\/watch?v=Q6eTlmkCYwk","target":"https:\/\/you-tube.eu\/youPHPTubeEncoder.json","postFields":12,"videoFileSize":"21.23MB","response_raw":"","response":null}
[03-Dec-2019 16:49:40 UTC] Encoder::sendFile videos_id=0, format=mp4
[03-Dec-2019 16:49:40 UTC] Duration found: 0:01:41
[03-Dec-2019 16:49:40 UTC] PHP Warning:  file_exists(): open_basedir restriction in effect. File(/usr/local/bin/youtube-dl) is not within the allowed path(s): (/var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/:/tmp/) in /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/objects/Encoder.php on line 1290
[03-Dec-2019 16:49:42 UTC] Encoder::sendFile sending file to https://you-tube.eu/youPHPTubeEncoder.json
[03-Dec-2019 16:49:42 UTC] Encoder::sendFile reading file from /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile_converted_SD.mp4
[03-Dec-2019 16:49:43 UTC] YouPHPTube-Streamer answer 
[03-Dec-2019 16:49:43 UTC] {"error":false,"format":"mp4","file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/videos\/11_tmpFile_converted_SD.mp4","resolution":"SD","videoDownloadedLink":"https:\/\/www.youtube.com\/watch?v=Q6eTlmkCYwk","target":"https:\/\/you-tube.eu\/youPHPTubeEncoder.json","postFields":12,"videoFileSize":"15.46MB","response_raw":"","response":null}
[03-Dec-2019 16:49:43 UTC] Encoder::sendFile videos_id=0, format=mp4
[03-Dec-2019 16:49:43 UTC] Duration found: 0:01:41
[03-Dec-2019 16:49:43 UTC] PHP Warning:  file_exists(): open_basedir restriction in effect. File(/usr/local/bin/youtube-dl) is not within the allowed path(s): (/var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/:/tmp/) in /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/objects/Encoder.php on line 1290
[03-Dec-2019 16:49:45 UTC] Encoder::sendFile sending file to https://you-tube.eu/youPHPTubeEncoder.json
[03-Dec-2019 16:49:45 UTC] Encoder::sendFile reading file from /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/videos/11_tmpFile_converted_Low.mp4
[03-Dec-2019 16:49:45 UTC] YouPHPTube-Streamer answer 
[03-Dec-2019 16:49:45 UTC] {"error":false,"format":"mp4","file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/videos\/11_tmpFile_converted_Low.mp4","resolution":"Low","videoDownloadedLink":"https:\/\/www.youtube.com\/watch?v=Q6eTlmkCYwk","target":"https:\/\/you-tube.eu\/youPHPTubeEncoder.json","postFields":12,"videoFileSize":"9.18MB","response_raw":"","response":null}
[03-Dec-2019 16:49:45 UTC] Autodelete Not active
[03-Dec-2019 16:49:45 UTC] Encoder::save id=(11) title=(More Office Pranks | Cartoon Box 157 | Hilarious Workplace Bullying Cartoon)[{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/objects\/Encoder.php","line":744,"function":"save","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/vhosts\/beta.mikweb.eu\/httpdocs\/YouPHPTube-Encoder\/view\/send.json.php","line":20,"function":"send","class":"Encoder","object":{},"type":"->","args":[]}]
logs  Stream#1 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/getImageFromFilenameAsync.php(2): require_once('/var/www/vhosts...')
#2 {main}
  thrown in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/include_config.php on line 9
[03-Dec-2019 17:32:34 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/include_config.php:9
Stack trace:
#0 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/videos/configuration.php(28): require_once()
#1 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/getImageFromFilenameAsync.php(2): require_once('/var/www/vhosts...')
#2 {main}
  thrown in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/include_config.php on line 9
[03-Dec-2019 17:32:34 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/include_config.php:9
Stack trace:
#0 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/videos/configuration.php(28): require_once()
#1 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/getImageFromFilenameAsync.php(2): require_once('/var/www/vhosts...')
#2 {main}
  thrown in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/include_config.php on line 9
[03-Dec-2019 17:32:34 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/include_config.php:9
Stack trace:
#0 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/videos/configuration.php(28): require_once()
#1 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/getImageFromFilenameAsync.php(2): require_once('/var/www/vhosts...')
#2 {main}
  thrown in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/include_config.php on line 9
[03-Dec-2019 17:32:34 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/include_config.php:9
Stack trace:
#0 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/videos/configuration.php(28): require_once()
#1 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/getImageFromFilenameAsync.php(2): require_once('/var/www/vhosts...')
#2 {main}
  thrown in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/objects/include_config.php on line 9
[03-Dec-2019 16:33:18 UTC] Bot Detected, NOT showing the cache (/robots.txt) FROM: 216.244.66.241 Browser: Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)
[03-Dec-2019 16:33:18 UTC] Bot stopped

**Comment by DanielnetoDotCom** [comment]
I found this ....

`open_basedir restriction in effect. File(/usr/local/bin/youtube-dl) is not within the allowed path(s):
`
and also this

`PHP Fatal error: Uncaught Error: Class 'mysqli' not found in `

I am pretty  sure you update your PHP or apache

**Comment by mikweb2017** [comment]
I'm sorry I don't understand what I have to do. 
I update the system regularly and a problem that?

**Comment by DanielnetoDotCom** [comment]
The errors above are not from the PHP, it looks like is the server.

try to reboot your server, also make sure the MySQL is running

**Comment by mikweb2017** [comment]
of course mysql online server the last time I was uploaded to the videos dates back to October 24.

i don't know what i have to do you have some other idea

**Comment by adelorenzo** [comment]
Hello,

I am having the same problem of encoded videos not being uploaded. In my case the error is as follows:

[03-Dec-2019 13:21:19 America/Chicago] PHP Fatal error:  Uncaught Error: Call to undefined function replace() in /opt/YouPHPTube/objects/security.php:17
Stack trace:
#0 /opt/YouPHPTube/objects/include_config.php(32): require_once()
#1 /opt/YouPHPTube/videos/configuration.php(29): require_once('/opt/YouPHPTube...')
#2 /opt/YouPHPTube/view/error.php(4): require_once('/opt/YouPHPTube...')
#3 {main}
  thrown in /opt/YouPHPTube/objects/security.php on line 17

All permissions, databases, etc are ok.

Please advise. Thank you very much.

Best

**Comment by mikweb2017** [comment]
check your demo site
https://demo.avideo.com/
I tried to upload a video and it seems the same problem

**Comment by DanielnetoDotCom** [comment]
@adelorenzo you were right, sorry about that, I just sent a fix

@mikweb2017 I will try now and see how is on the demo site

**Comment by DanielnetoDotCom** [comment]
I just fount the encoder will need to be updated as well for the rebranding

**Comment by adelorenzo** [comment]
It's working perfectly now! thank you sooo much and congrats for the project.

Best,

Adolfo

**Comment by mikweb2017** [comment]
It's work again for me  tanks
